version: "3.7"

services:

  app:    
    build: .
    container_name: rentalx
    ports:
      - 3333:3333
      - 9229:9229 # porta para usar no debug na aplicacao...
    volumes:
      - .:/usr/app
    networks:
      - rentalx-net
    depends_on:
      - rentalxdb
  
  rentalxdb:
    image: postgres:14.2
    container_name: rentalxdb
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
    networks:
      - rentalx-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    networks:
      - rentalx-net
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=marcus.vbrangel@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=5678
    volumes:
      - pgadmin:/root/.pgadmin

volumes:
  pgdata:
  pgadmin:
    #driver: local

networks:
  rentalx-net:
    driver: bridge
